# by SocialMoods

# _________             .__       .__      _____                    .___
# /   _____/ ____   ____ |__|____  |  |    /     \   ____   ____   __| _/______
# \_____  \ /  _ \_/ ___\|  \__  \ |  |   /  \ /  \ /  _ \ /  _ \ / __ |/  ___/
# /        (  <_> )  \___|  |/ __ \|  |__/    Y    (  <_> |  <_> ) /_/ |\___ \
# /_______  /\____/ \___  >__(____  /____/\____|__  /\____/ \____/\____ /____  >
# \/            \/        \/              \/                   \/    \/

# Спиздил или слил плагин - пидорас.


# Предметы добавляются по форме ниже
# Плагин создан специально для MorfoseTime и подходит только к этому серверу

# "слот":
#   itemId: <ID предмета>
#   count: <количество>
#   price: <цена>

"0":
  itemId: 265 # Железный слиток
  count: 15
  price: 100

"1":
  itemId: 266 # Золотой слиток
  count: 10
  price: 200

"2":
  itemId: 264 # Алмаз
  count: 5
  price: 500


